server {
    listen 80;
    server_name _;

    # Sirve la aplicación React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Inverso hacia el backend de Despachos vía DNS interno de K8s
    location /api/despachos/ {
        proxy_pass http://back-despacho-svc:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy Inverso hacia el backend de Ventas vía DNS interno de K8s
    location /api/ventas/ {
        proxy_pass http://back-ventas-svc:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}